### ISSUE TITLE
gtk::TextBuffer::new::(None) doesn't compile on gtk-rs v0.6

### ISSUE THREAD

**Issue by Susurrus** [gtk-rs/gtk#790]
I had code on previous versions that looked like:
```rust
    let hex_buffer = gtk::TextBuffer::new(None);
```

That used to compile, however with the recent 0.6 release, I now get the following error:
```
error[E0283]: type annotations required: cannot resolve `_: glib::IsA<gtk::TextTagTable>`                                                                                                 
   --> src/bin/gattii.rs:416:23                                                                                                                                                           
    |                                                                                                                                                                                     
416 |     let text_buffer = gtk::TextBuffer::new(None);                                                                                                                                   
    |                       ^^^^^^^^^^^^^^^^^^^^                                                                                                                                          
    |                                                                                                                                                                                     
    = note: required by `gtk::TextBuffer::new` 
```

I thought I had this issue before with some of my GTK code, but I couldn't find it. The compiler wasn't helpful either when running `rustc --explain E0283`.

Most reference I see to "type annotations" refer to the turbofish syntax, but even changing it to be `let hex_buffer = gtk::TextBuffer::new::<gtk::TextTableTag>(None);` results in this error:
```
error[E0107]: wrong number of type arguments: expected 2, found 1                                                                                                                         
   --> src/bin/gattii.rs:420:22                                                                                                                                                           
    |                                                                                                                                                                                     
420 |     let hex_buffer = gtk::TextBuffer::new::<gtk::TextTagTable>(None);                                                                                                               
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 2 type arguments                                                                                            
```

but `gtk::TextBuffer::new()` only takes 1 argument. So I'm a little stuck on what to do here.

**Comment by GuillaumeGomez** [comment]
You have to give the type parameter to `None` directly: `None::<gtk::TextTagTable>`. We're not very happy on how we handled the `Into` trait. It'll be removed in the next release. Sorry for the inconvenience.

**Comment by sdroege** [comment]
See https://github.com/gtk-rs/gir/issues/722

**Comment by Susurrus** [comment]
Thanks for the help. I didn't realize I needed the annotation on `None`. For those following along from home, the correct solution was:
```rust
let hex_buffer = gtk::TextBuffer::new(None::<gtk::TextTagTable>);
```

Because there's already an issue tracking this work, I'll go ahead and close this now.

**Comment by GuillaumeGomez** [comment]
We indeed to add documentation about this. For the moment, we can't do better than this unfortunately...

**Comment by theIDinside** [comment]
This btw, does not work either, since as a parameter it takes a Option<&TextTagTable> as the type. However, there seem to be constants defined in gtk, so gtk::NONE_TEXT_TAG_TABLE work, since it's defined as. 
```rust
pub const NONE_TEXT_TAG_TABLE: Option<&TextTagTable> = None;
```

Also, passing None::<&gtk::TextTagTable> works, of course.

**Comment by sdroege** [comment]
@theIDinside is there something broken, something that does not work or what do you mean?
